language: python
python:
 - "2.7"
 - "3.6"

dist: xenial
env: PYTHONDONTWRITEBYTECODE=true
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

install:
  - pip install -U -q pip
  - pip install -r requirements.txt

script: 
  - make tests
